<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>cloud.xcan.agentx</groupId>
    <artifactId>agentx-vectorstore</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>agentx-vectorstore-weaviate</artifactId>
  <name>AgentX :: Vector Store :: Weaviate</name>

  <dependencies>
    <dependency>
      <groupId>cloud.xcan.agentx</groupId>
      <artifactId>agentx-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-weaviate</artifactId>
    </dependency>
  </dependencies>
</project>
