package cloud.xcan.angus.core.ai.application.converter;

import cloud.xcan.angus.core.ai.domain.dataset.DatasetData;
import cloud.xcan.angus.core.ai.domain.dataset.DatasetDataStatus;
import cloud.xcan.angus.core.ai.domain.dataset.DatasetDataType;
import org.jetbrains.annotations.NotNull;
import org.springframework.web.multipart.MultipartFile;

public class DatasetDataConverter {

  public static @NotNull DatasetData toDatasetData(
      Long datasetId, MultipartFile file, String original) {
    DatasetData data = new DatasetData();
    // id will be generated by DB
    data.setDatasetId(datasetId);
    data.setName(original);
    // rudimentary type detection
    if (original.endsWith(".csv")) {
      data.setType(DatasetDataType.CSV);
    } else if (original.endsWith(".xlsx") || original.endsWith(".xls")) {
      data.setType(DatasetDataType.EXCEL);
    } else {
      data.setType(DatasetDataType.EXCEL);
    }
    data.setStatus(DatasetDataStatus.UPLOADING);
    data.setDataCount(0L);
    data.setDataSize(file.getSize());
    return data;
  }

}
