<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>cloud.xcan.agentx</groupId>
    <artifactId>xcan-angusai.agentx-parent</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>xcan-angusai.agentx-model-providers</artifactId>
  <packaging>pom</packaging>
  <name>AgentX :: Model Providers</name>

  <modules>
    <module>agentx-model-openai</module>
    <module>agentx-model-anthropic</module>
    <module>agentx-model-ollama</module>
    <module>agentx-model-gemini</module>
    <module>agentx-model-qwen</module>
    <module>agentx-model-zhipu</module>
    <module>agentx-model-deepseek</module>
  </modules>
</project>
